/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CostureirasIndexRouteImport } from './routes/costureiras.index'
import { Route as CostureirasIdRouteImport } from './routes/costureiras.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CostureirasIndexRoute = CostureirasIndexRouteImport.update({
  id: '/costureiras/',
  path: '/costureiras/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostureirasIdRoute = CostureirasIdRouteImport.update({
  id: '/costureiras/$id',
  path: '/costureiras/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/costureiras/$id': typeof CostureirasIdRoute
  '/costureiras/': typeof CostureirasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/costureiras/$id': typeof CostureirasIdRoute
  '/costureiras': typeof CostureirasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/costureiras/$id': typeof CostureirasIdRoute
  '/costureiras/': typeof CostureirasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/costureiras/$id' | '/costureiras/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/costureiras/$id' | '/costureiras'
  id: '__root__' | '/' | '/about' | '/costureiras/$id' | '/costureiras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CostureirasIdRoute: typeof CostureirasIdRoute
  CostureirasIndexRoute: typeof CostureirasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costureiras/': {
      id: '/costureiras/'
      path: '/costureiras'
      fullPath: '/costureiras/'
      preLoaderRoute: typeof CostureirasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costureiras/$id': {
      id: '/costureiras/$id'
      path: '/costureiras/$id'
      fullPath: '/costureiras/$id'
      preLoaderRoute: typeof CostureirasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CostureirasIdRoute: CostureirasIdRoute,
  CostureirasIndexRoute: CostureirasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
